sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t prince/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true prince/docker-react npm run test
  